const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

try {
    console.log('Generating autolinking configuration...');
    const output = execSync('npx @react-native-community/cli config', { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'inherit'] });
    const match = output.match(/\{[\s\S]*\}/);
    if (!match) throw new Error('Could not find JSON in CLI output');

    const config = JSON.parse(match[0]);
    let gradleContent = '// Generated by autolinking.js\n\n';

    // Ensure the autolinking.json exists for the :app project
    const buildDir = path.join(__dirname, 'android/build/generated/autolinking');
    if (!fs.existsSync(buildDir)) fs.mkdirSync(buildDir, { recursive: true });
    fs.writeFileSync(path.join(buildDir, 'autolinking.json'), match[0]);

    if (config.dependencies) {
        Object.keys(config.dependencies).forEach(name => {
            const dependency = config.dependencies[name];
            if (dependency.platforms && dependency.platforms.android && dependency.platforms.android.sourceDir) {
                // Exact name cleansing logic
                const nameCleansed = name.replace(/[~*!'()]+/g, "_").replace(/^@([\w-.]+)\//, "$1_");
                const sourceDir = dependency.platforms.android.sourceDir.replace(/\\/g, '/');
                gradleContent += `include ":${nameCleansed}"\n`;
                gradleContent += `project(":${nameCleansed}").projectDir = new File("${sourceDir}")\n`;
            }
        });
    }

    fs.writeFileSync(path.join(__dirname, 'android/autolinking.gradle'), gradleContent);
    console.log('Successfully generated autolinking.gradle and autolinking.json');
} catch (error) {
    console.error('Failed to generate autolinking:', error.message);
    process.exit(1);
}
